### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by gagarski** [Shalyapin-Polytech/Minesweeper#2]
1. Сразу бросилось в глаза: зачем в солвере `AtomicBoolean`?
2. В `solve` рекурсия на ровном месте, можно легко обойтись циклом.
3. Очень сомнительное решение - наследоваться от стандартного `HashSet`
4. Почему местами `for`, а местами `.forEach`?

**Comment by perfect-insanity** [comment]
1. Остался от прошлого варианта, заменил на простой `boolean`.
2. Исправил на `do`-`while`.
3. А чем плох такой вариант?
4. Теперь все через `.forEach`.
